**Description**  
In this notebook will be implemented 1d convolution operation.

In [ ]:
import numpy as np

**Auxiliary functions**

In [ ]:
def rotate_vector(vector):
  rotated = []
  for i in range(len(vector)):
    rotated.append(vector[len(vector)-1-i])
  return rotated

In [ ]:
def dot_product(arr1, arr2):
  assert len(arr1) == len(arr2), "For dot product vectors should be of same length"
  res = 0
  for i in range(len(arr1)):
    res += arr1[i]*arr2[i]
  return res

**Main function realisation**

In [ ]:
def conv1d(arr_in, kernel, step, padding=0):
  arr_out = []
  assert step != 0, "Step should be > 0"
  assert len(kernel) <= len(arr_in), "Kernel should be smaller than input array"
  assert padding >= 0, "Padding should be > 0"
  assert len(kernel) != 0, "Kernel cannot be empty"
  arr_in = [0]*padding + arr_in + [0]*padding
  kernel = rotate_vector(kernel)
  for i in range(0, len(arr_in)-len(kernel) + 1, step):
    arr_out.append(dot_product(arr_in[i:i+len(kernel)], kernel))
  return arr_out

**Some tests**  
Comparing to implemented function *convolve* from module *numpy*

In [ ]:
print(conv1d(arr_in = [1, 0, 2, 3, 4, 1, 0, 9], kernel=[1, 0, 1, 0], step=1))
np.convolve([1, 0, 2, 3, 4, 1, 0, 9], [1, 0, 1, 0], 'valid')

[3, 6, 4, 4, 10]


array([ 3,  6,  4,  4, 10])

In [ ]:
print(conv1d(arr_in = [1, 2, 3, 4, 5], kernel=[1, 0, -1], step=1))
np.convolve([1, 2, 3, 4, 5], [1, 0, -1], 'valid')

[2, 2, 2]


array([2, 2, 2])

In [ ]:
print(conv1d(arr_in = [1, 2, 3, 4, 5, 0], kernel=[], step=1))
np.convolve([1, 2, 3, 4, 5], [], 'valid')

AssertionError: Kernel cannot be empty

In [ ]:
np.convolve([1, 2, 3, 4, 5], [], 'valid')

ValueError: v cannot be empty

In [ ]:
print(conv1d(arr_in = [3, 6, 8, 2, 1, 4, 7, 9], kernel=[4, 0, 6, 3, 2], step=1, padding=2))
np.convolve([3, 6, 8, 2, 1, 4, 7, 9], [4, 0, 6, 3, 2], 'same')

In [ ]:
print(conv1d(arr_in = [1, 2, 3], kernel = [0, 1, 0.5], step=1))
np.convolve([1, 2, 3], [0, 1, 0.5], 'valid')

[2.5]


array([2.5])

In [ ]:
print(conv1d(arr_in = [1, 2, 3], kernel = [0, 1, 0.5], padding=2, step=1))
np.convolve([1, 2, 3], [0, 1, 0.5])

[0.0, 1.0, 2.5, 4.0, 1.5]


array([0. , 1. , 2.5, 4. , 1.5])

**Kernel size**  
Too big kernel will shrink size of initial data file greatly(can be addressed as noise deletion),  but from other side will also not preserve much of important information present in initial file. The reverse relationship exists for too small kernels (too small kernel will preserve too much of initial noise). So, it is very important picking up kernels of the right size that will considerably reduce size of initial data , as well as preserve acceptable amount of important information from initial data.

For example, let's consider following two cases:   
1) used smaller kernel;   
2) used much bigger kernel;   
In case of smaller kernel was obtained processed array that contains much  detailed information about structure of initial array, comparing to processed array from second case.  
Though, in second case was obtained much smaller array comparing to obtained in first case.

In [ ]:
print(conv1d(arr_in = [1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, -100, -100, -100, -100, -100, 100, 100, 100, 100, 100, 23, 23, 23, 23, 23], kernel=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], step=1))


[25, 24, -77, -178, -279, -380, -484, -388, -292, -196, -100, 0, 23, 46, 69, 92, 215]


In [ ]:
print(conv1d(arr_in = [1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, -100, -100, -100, -100, -100, 100, 100, 100, 100, 100, 23, 23, 23, 23, 23], kernel=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], step=1))

[-75, 24, 46, 68, 90, 112, 131]
